### ISSUE TITLE
[Meta] Repo cleanup

### ISSUE THREAD

**Issue by Just-Jojo** [Just-Jojo/JojoCogs#24]
I wanna try and get CC for Red (maybe?) so I'll need to do some cleaning up as this repo is a mess 😄 

- [x] Add some more files for help (eg. issues and stuff)
- [x] Spice up Calculations as it's not fun atm
- [x] Function/method updates to make it easier and cleaner
- [x] **No security issues**. I doubt I have any but it would be wise to look through and make sure

Deadline (lmfao, a deadline) should be the end of the month but idk

**Comment by Just-Jojo** [comment]
Done! :D
